Add Kustomize artifacts for deploying rsyslog
AICoE/internal-data-hub pull request #1
Opened 2020-09-29 14:47 UTC by accorvin

2020-09-29 14:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-09-29 17:29 UTC, HumairAK reviewed
one minor comment above, but other than that lgtm!

2020-09-29 17:29 UTC, HumairAK commented on rsyslog/README.md
> +Run the following command from the root of this repository to deploy
> from the root of this repository 

I think you meant from the `rsyslog` folder, otherwise you should prepend the following paths to be `rsyslog/overlays/...` etc.

2020-09-29 17:35 UTC, accorvin commented on rsyslog/README.md
> +Run the following command from the root of this repository to deploy
Fixed, thanks!

2020-09-29 17:52 UTC, HumairAK approved these changes

2020-09-29 17:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-498738547" title="Approved">HumairAK</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-09-29 18:12 UTC, anishasthana requested changes

2020-09-29 18:12 UTC, anishasthana commented on rsyslog/README.md
> +Kustomize deployment for the Data Hub's internal Jupyterhub instance
`Jupyterhub`

2020-09-29 18:12 UTC, anishasthana commented on rsyslog/bases/rsyslog/rsyslog.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-rsyslog.git
Can we bring the contents of this repository out as well? Or should it stay internal for now?

2020-09-30 12:54 UTC, accorvin commented on rsyslog/bases/rsyslog/rsyslog.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-rsyslog.git
@anishasthana I've been trying to think of a good solution for that. If I can get a repo set up in a good spot in Quay, what do you think of moving this code to this repo then setting up a quay build for it rather than building the image in a build config?

2020-09-30 13:04 UTC, accorvin commented on rsyslog/README.md
> +Kustomize deployment for the Data Hub's internal Jupyterhub instance
Fixed.

2020-09-30 13:04 UTC, accorvin commented on rsyslog/bases/rsyslog/rsyslog.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-rsyslog.git
For now, I've added the image build artifacts to this PR and updated the buildconfig to point to them.

2020-09-30 13:15 UTC, anishasthana commented on rsyslog/bases/rsyslog/rsyslog.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-rsyslog.git
I like that.

2020-09-30 13:20 UTC, anishasthana approved these changes

2020-09-30 13:20 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-499421368" title="Approved">anishasthana</a>*, *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-498738547" title="Approved">HumairAK</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-09-30 14:00 UTC, HumairAK commented
I don't see a .sops.yaml file included in the target-env folders that use sops, could you add those?

2020-09-30 14:16 UTC, accorvin commented
> I think you're missing the .sops.yaml file included in the target-env folders that use sops, could you add those?

@HumairAK Ah, good catch. I missed that when copying files over from the old PR since it's a hidden file.

Is it supposed to be in the target env directories, or just the main rsyslog directory? I've added it in this PR now in the main rsyslog directory, which looked like how it was done in other examples.

2020-09-30 14:22 UTC, HumairAK commented
@accorvin  it depends on your use case, so if stage/prod are encrypted using different gpg fingerprints then you'd use .sops.yaml for each directory (sops looks for the closest .sops.yaml in the file tree hierarchy), same if you have a different _regex_ or other configs

2020-09-30 14:23 UTC, HumairAK approved these changes

2020-09-30 14:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-499421368" title="Approved">anishasthana</a>*, *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-499486701" title="Approved">HumairAK</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-09-30 15:02 UTC, anishasthana approved these changes

2020-09-30 15:02 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-499529283" title="Approved">anishasthana</a>*, *<a href="https://github.com/AICoE/internal-data-hub/pull/1#pullrequestreview-499486701" title="Approved">HumairAK</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-09-30 15:03 UTC, merged