WIP: Kustomize logstash
AICoE/internal-data-hub pull request #24
Opened 2020-11-17 03:54 UTC by gmfrasca

- DATAHUB-2475

this is comparable to master of (internal) container-logstash.  However, ArgoCD is detecting diffs in the actual prod-deployed objects, (different base repos/images, configmap names, etc) so I'm not sure which we want to call the source of truth.

2020-11-17 03:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **gmfrasca** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @gmfrasca` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gmfrasca"]} -->

2020-11-17 03:56 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: logstash/container-image/build-image.sh by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing logstash/container-image/README.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing logstash/container-image/run-container.sh
Fixing logstash/container-image/install.sh

Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
yamllint.................................................................Passed
```
</details>

2020-11-17 14:03 UTC, anishasthana requested changes

2020-11-17 14:03 UTC, anishasthana commented on logstash/container-image/README.md
> +# TODO: this seems like copypasta from rsyslog and fluentd READMEs and not related to logstash?
Seems like it. Any thoughts on what it should instead be?

2020-11-17 14:10 UTC, anishasthana commented
Can you also fix the pre-commit checks?

2020-11-18 08:36 UTC, gmfrasca commented on logstash/bases/logstash/logstash.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-monitoring.git
I feel like that is outside the scope of this PR, which is to simply convert the current deployment to Kustomize.  In fact, I'm on the fence about the build pointer change of logstash itself from `container-logstash` to this repository as well, as this introduces the possibility divergent images.

2020-11-18 08:37 UTC, gmfrasca commented on logstash/container-image/README.md
> +# TODO: this seems like copypasta from rsyslog and fluentd READMEs and not related to logstash?
I'll just update to be relevant to logstash...most of the content here also works and just needs some simple adaptations in language.

2020-11-18 13:52 UTC, accorvin commented on .gitignore
> +*.plaintext.*
I like this convention.

2020-11-18 14:02 UTC, accorvin commented on logstash/bases/logstash/logstash.yaml
> +      generation: 2
I _think_ that the `generation` field is not necessary. Same with the `importPolicy`field below. Note that these same fields appear on other image streams below.

2020-11-18 14:03 UTC, accorvin commented on logstash/bases/logstash/logstash.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-monitoring.git
I think it's a good idea to move them over, but I agree that that's outside the scope of this PR. Let's add a later task to do it.

2020-11-18 14:05 UTC, accorvin commented on logstash/overlays/dev/logstash.yaml
> +kind: BuildConfig
Why was it necessary to override this buildconfig?

2020-11-18 14:58 UTC, anishasthana commented on logstash/bases/logstash/logstash.yaml
> +      uri: https://gitlab.cee.redhat.com/data-hub/dh-monitoring.git
I've created https://github.com/AICoE/internal-data-hub/issues/27

2020-11-18 16:04 UTC, gmfrasca commented on logstash/bases/logstash/logstash.yaml
> +      generation: 2
I initially did not include them but the app diff showed they were missing vs what is currently in production

2020-11-18 16:15 UTC, accorvin commented on logstash/bases/logstash/logstash.yaml
> +      generation: 2
hmmm, alright. I'm concerned that this will break upon future builds of the image. I would bet that if we were to remove these fields and let ArgoCD apply the diff that it would resolve itself. I'm pretty sure we don't have these fields for other imagestreams, e.g. for rsyslog.

2020-11-18 16:28 UTC, anishasthana commented on logstash/bases/logstash/logstash.yaml
> +      generation: 2
I don't think we'd need it either.

2020-11-20 16:17 UTC, anishasthana requested changes

2020-11-20 16:17 UTC, anishasthana commented on logstash/bases/logstash/logstash.yaml
> +        name: quay.io/anishasthana/python-35-centos7
This image needs to be pointed to something in the internaldatahub organization on quay.

2020-11-20 16:47 UTC, anishasthana commented on logstash/bases/logstash/logstash.yaml
> +        name: quay.io/internaldatahub/python-35-centos7
You're going to hate me. Can we use a tagged version here?

2020-11-20 19:12 UTC, anishasthana commented
/hold

2020-11-20 19:22 UTC, anishasthana approved these changes
lgtm

2020-11-20 19:22 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/24#pullrequestreview-535714640" title="Approved">anishasthana</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/master/OWNERS)~~ [anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-20 19:24 UTC, anishasthana commented on logstash/overlays/dev/logstash.yaml
> +kind: BuildConfig
Fixed.

2020-11-20 19:27 UTC, gmfrasca commented
/unhold

2020-11-20 19:27 UTC, merged