WIP: Camel k integration
AICoE/internal-data-hub pull request #245
Opened 2022-02-04 14:31 UTC by lucferbux

Just a wip to discuss the integration, I haven't squashed all the commits cause i wanted to have everything sorted out first.

2022-02-04 14:32 UTC, sesheta commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2022-02-04 14:32 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **lucferbux** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["lucferbux"]} -->

2022-02-04 14:39 UTC, anishasthana requested changes
Have you opened a ticket with PSI yet for the operator group?

2022-02-04 14:39 UTC, anishasthana commented on camelk/base/integration-platform.yaml
> +    app: "camel-k"
Missing new line character

2022-02-04 14:39 UTC, anishasthana commented on camelk/base/subscription.yaml
> +  startingCSV: red-hat-camel-k-operator.v1.6.3
This can be a dangerous thing to have in the subscription (if they eventually get rid of the CSV). Imo I'd remove it

2022-02-04 14:39 UTC, anishasthana commented on camelk/overlays/prod/kustomization.yaml
> +  - operator-group.yaml
We do not have the right to create operator groups in prod. I'd do something similar to https://github.com/AICoE/internal-data-hub/tree/main/grafana/overlays/prod instead

2022-02-04 15:30 UTC, lucferbux commented on camelk/base/subscription.yaml
> +  startingCSV: red-hat-camel-k-operator.v1.6.3
👌

2022-02-04 15:30 UTC, lucferbux commented on camelk/overlays/prod/kustomization.yaml
> +  - operator-group.yaml
👌

2022-02-04 15:51 UTC, lucferbux commented
> Have you opened a ticket with PSI yet for the operator group?

yes

2022-02-04 15:53 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | b713dda61ccb72386e0d279d087d8dee230a868a | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_internal-data-hub/245/pre-commit/1489627864587309056) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=245). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-07 19:02 UTC, anishasthana reviewed
/lgtm

2022-02-07 19:54 UTC, gmfrasca approved these changes

2022-02-07 19:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/245#pullrequestreview-875178428" title="Approved">gmfrasca</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)~~ [gmfrasca]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-07 19:57 UTC, merged