Added kafka2trino integration to camelk
AICoE/internal-data-hub pull request #260
Opened 2022-02-11 16:34 UTC by lucferbux

Adapted camel k operator and added a kafka2trino integration for some topic

2022-02-11 16:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **lucferbux** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["lucferbux"]} -->

2022-02-11 16:45 UTC, anishasthana requested changes

2022-02-11 16:45 UTC, anishasthana commented on camelk/base/kafka2trino.yaml
> +  name: kafka2trino
We should use a different name for this. My assumption is that we will have a separate integration for each topic, so our options are:
1. Keep current `kafka2trino.yaml` file, and have a list of integration objects within it.
2. Delete this file, create a separate `integration-<topic_name>` file for each topic.

I _think_ I'm liking the first option better.

2022-02-11 16:50 UTC, lucferbux commented on camelk/base/kafka2trino.yaml
> +  name: kafka2trino
👌

2022-02-11 17:53 UTC, anishasthana reviewed
/lgtm

2022-02-11 18:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **anishasthana** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["anishasthana"]} -->

2022-02-14 15:04 UTC, rimolive commented
/approve

2022-02-14 15:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/260#issuecomment-1039192960" title="Approved">rimolive</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)~~ [rimolive]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-14 15:07 UTC, merged