Adding minio dependencies required for KFP
AICoE/internal-data-hub pull request #314
Opened 2022-04-21 16:20 UTC by DharmitD

Pulled down YAMLs added/utilized on the following dev cluster:
https://console-openshift-console.apps.ddalvi-dev.dev.datahub.redhat.com/k8s/ns/kubeflow/deployments 
that we used to create a toy KubeFlow Pipeline.

2022-04-21 16:20 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **dharmitd** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["dharmitd"]} -->

2022-04-21 16:33 UTC, gmfrasca requested changes

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +  annotations:
most of this metadata we don't need.  I'd just keep `labels` and `name` and delete everything else

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +metadata:
same here

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
I'm not sure this file is needed, this is pretty specific to the actual toy pipeline

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +metadata:
same here

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +status:
we shouldn't have `status` in any of our deployement artifacts, delete this

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +status:
delete `status`

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
remove unnecessary metadata

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +metadata:
remove unnecessary metadata

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +status:
delete `status`

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
> +metadata:
remove unnecessary metadata

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/services/minio-service.yaml
> +status:
delete `status`

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/services/minio-service.yaml
> +metadata:
remove unnecessary metadata

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
> +  accesskey: MTIzNGVy
erm, is this supposed to actually be secret?

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +  volumeName: pvc-3eaf193b-80a4-438b-951c-dfe4cce7440c
i feel like this is likely fragile/incorrect?

2022-04-21 16:33 UTC, gmfrasca commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +  artifact_script: |-
was this actually used?  seems related to thoth, not kfp but i could be wrong here

2022-04-21 16:35 UTC, gmfrasca commented
also, this appears to be a dump of flat .yaml files.  That's fine, but i think there needs to be an update made to the kustomize.yaml (or add one if it doesn't yet exist) for this overlay

2022-04-21 18:56 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
Yes, this file is specific to the actual pipeline, we had added it on the cluster separately. Taking it out.

2022-04-21 20:48 UTC, anishasthana requested changes
Started reviewing but Giulio seems to have everything covered

2022-04-21 20:48 UTC, anishasthana commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +  artifact_script: |-
Ah this is actually important. I'd leave it in. kfp is an annoyance

2022-04-21 20:48 UTC, anishasthana commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +    kubectl.kubernetes.io/last-applied-configuration: |
Remove lines 35-37 and lines 42-43

2022-04-21 20:48 UTC, anishasthana commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
I'd force push and delete it

2022-04-21 20:48 UTC, anishasthana commented on kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
> +  accesskey: MTIzNGVy
It's a garbage secret, so don't really need to worry about it. Honestly, best process would probably be to ksops it, but _shruggie_

2022-04-22 03:17 UTC, DharmitD commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +  volumeName: pvc-3eaf193b-80a4-438b-951c-dfe4cce7440c
This is the file on the cluster that I've pulled down as is:
https://console-openshift-console.apps.ddalvi-dev.dev.datahub.redhat.com/k8s/ns/kubeflow/persistentvolumeclaims/minio-pvc/yaml

This is what this file looks like in the operate-first commit (which we used as a reference for adding all these yamls to the cluster):
https://github.com/operate-first/apps/blob/c019daf9e4889e5f3e0129a4aeb0da533470de4e/kfp-tekton/base/persistentvolumeclaims/minio-pvc.yaml

So I guess I can take out everything lines 26 onwards?

2022-04-22 03:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +  annotations:
Done, just left `labels` and `name` in metadata.

2022-04-22 03:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +metadata:
Done, just left `labels` and `name` in metadata.

2022-04-22 03:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
Deleted the file.

2022-04-22 16:40 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
Done, deleted this file.

2022-04-22 16:40 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +metadata:
Done, just left `labels` and `name` in metadata.

2022-04-22 16:41 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +status:
Done, took `status` out.

2022-04-22 16:43 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +status:
Done, took `status` out.

2022-04-22 16:44 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
Done, just left `labels` and `name` in metadata.

2022-04-22 16:44 UTC, DharmitD commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +metadata:
Done, just left `labels` and `name` in metadata.

2022-04-22 16:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
> +metadata:
Done, just left `labels` and `name` in metadata.

2022-04-22 16:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +status:
Done, took `status` out.

2022-04-22 16:52 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
> +    kubectl.kubernetes.io/last-applied-configuration: |
Done, took them out.

2022-04-22 17:38 UTC, DharmitD commented on kfp-tekton/overlays/dev/configmaps/telemetry-access-config.yaml
> +apiVersion: v1
> I see a kustomization.yaml file already for the dev overlay:
https://github.com/AICoE/internal-data-hub/blob/main/kfp-tekton/overlays/dev/kustomization.yaml
So would I need to just add paths to the configmaps, deployments, secrets, etc we've added within resources? Like they've done it here for operate first?
https://github.com/operate-first/apps/blob/c019daf9e4889e5f3e0129a4aeb0da533470de4e/kfp-tekton/base/kustomization.yaml#L37-L70

2022-04-22 17:40 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
> also, this appears to be a dump of flat .yaml files. That's fine, but i think there needs to be an update made to the kustomize.yaml (or add one if it doesn't yet exist) for this overlay

I see a kustomization.yaml file already for the dev overlay:
https://github.com/AICoE/internal-data-hub/blob/main/kfp-tekton/overlays/dev/kustomization.yaml
What updates would I need to make to this one then? Just add paths to the configmaps, deployments, secrets, etc we've added within resources? Like they've done it here for operate first?
https://github.com/operate-first/apps/blob/c019daf9e4889e5f3e0129a4aeb0da533470de4e/kfp-tekton/base/kustomization.yaml#L37-L70

2022-04-22 19:44 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +metadata:
erm, still has it here looks like

2022-04-22 19:48 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
RE: kustomize.yaml - yes, assuming these files are net-new (they aren't overlaying other files in `../../base`, I would just add their relative paths to the `resources` dict in the pre-existing kustomize.yaml found in this `dev` folder.

With that said, we'll probably eventually need to transfer these files to base, but thats a problem for another day.

2022-04-22 19:48 UTC, gmfrasca commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
also, looks like you missed removing the unnecessary metadata here

2022-04-22 23:46 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
Oops. Done, removed the unnecessary metadata.

2022-04-22 23:47 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
> +metadata:
And updated the kustomize.yaml to have relative paths under `resources` too

2022-04-25 23:21 UTC, DharmitD commented
Updated the `kustomize.yaml` to use `patchesStrategicMerge` for the yamls that were already in the base too. Tried running locally using the `kustomize build --enable-alpha-plugins` command and verified that all these changes work.

2022-04-25 23:25 UTC, sesheta commented
@DharmitD: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 68cbe68604a3307bcf84136e7b44fb0c2cd544ac | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_internal-data-hub/314/pre-commit/1518732372382584832) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=314). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3ADharmitD). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-26 15:29 UTC, anishasthana requested changes

2022-04-26 15:29 UTC, anishasthana commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +  volumeName: pvc-3eaf193b-80a4-438b-951c-dfe4cce7440c
I think this still needs to be removed

2022-04-26 15:49 UTC, DharmitD commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +  volumeName: pvc-3eaf193b-80a4-438b-951c-dfe4cce7440c
So wait, remove the whole file, or just lines 12-15?

2022-04-26 16:03 UTC, sesheta commented
@DharmitD: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 977938d69490be74394efcc171f58fcdc4cd4922 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_internal-data-hub/314/pre-commit/1518983731568709632) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=314). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3ADharmitD). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-26 18:08 UTC, DharmitD commented on kfp-tekton/overlays/dev/kustomization.yaml
> +# ConfigMaps
I'd added comments to replicate the operator-first commit, they'd added comments this way,

Done, took the comments out.

2022-04-26 20:53 UTC, sesheta commented
@DharmitD: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 914a7a28e3bffc186f63e9f3b7f80819725dc911 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_internal-data-hub/314/pre-commit/1519056882323427328) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=314). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3ADharmitD). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-26 21:07 UTC, DharmitD commented on kfp-tekton/overlays/dev/deployments/minio.yaml
> +metadata:
Done, took everything else out.

2022-04-26 21:07 UTC, DharmitD commented on kfp-tekton/overlays/dev/services/minio-service.yaml
> +status:
Done, took it out.

2022-04-26 21:08 UTC, DharmitD commented on kfp-tekton/overlays/dev/services/minio-service.yaml
> +metadata:
done

2022-04-26 21:08 UTC, DharmitD commented on kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
> +  volumeName: pvc-3eaf193b-80a4-438b-951c-dfe4cce7440c
Done, removed those lines.

2022-05-03 18:08 UTC, gmfrasca approved these changes

2022-05-03 18:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/314#pullrequestreview-960780901" title="Approved">gmfrasca</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)~~ [gmfrasca]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-05-03 18:22 UTC, merged