Use rover groups for usir access
AICoE/internal-data-hub pull request #431
Opened 2022-08-19 20:46 UTC by accorvin

2022-08-19 20:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **accorvin** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["accorvin"]} -->

2022-08-23 13:58 UTC, anishasthana requested changes

2022-08-23 13:58 UTC, anishasthana commented on kfdefs/base/trino/trino-group-mapping.properties
> +>>>>>>> 73e16a6 (Use rover groups for usir access)
Looks like a merge conflict was accidentally committed in.

2022-08-23 13:59 UTC, accorvin commented on kfdefs/base/trino/trino-group-mapping.properties
> +>>>>>>> 73e16a6 (Use rover groups for usir access)
good catch. stand by.

2022-08-23 14:09 UTC, accorvin commented on kfdefs/base/trino/trino-group-mapping.properties
> +>>>>>>> 73e16a6 (Use rover groups for usir access)
@anishasthana fixed.

2022-08-23 14:24 UTC, gmfrasca reviewed
/lgtm

2022-08-23 15:01 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/431#pullrequestreview-1082344444" title="Approved">anishasthana</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)~~ [anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-08-23 15:02 UTC, merged