first version with dev deploy -- DO NOT MERGE
AICoE/internal-data-hub pull request #56
Opened 2021-06-28 17:09 UTC by lucferbux

Ok, so here's the draft, I'm working on it, currently the patches are applied to the overlay and it seems working great, but I haven't been able to deploy it for several reasons, I might need a hand:

1. I am not sure what to do with the Ansible Secrets in certain files such as all of `j2/` and `certs/prod` folders. I am able to decypher them with the Ansible Vault utility but I have no idea how to port them, maybe k8 secrets, but then again these are j2 templates.
2. I am not sure/able to configure the secrets with ksops, I am not sure how to translate the secrets.yaml folder in order to use it in the overlays.
3. I don't know if pyscripts.Dockerfile will be called inside `bases/image.yaml` as the reference it's not clear, that would be an easy fix but I need to be able to deploy it in order to test it.

2021-06-28 17:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **anishasthana** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @anishasthana` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["anishasthana"]} -->

2021-06-28 17:09 UTC, lucferbux commented
@gmfrasca @anishasthana

2021-06-29 16:01 UTC, lucferbux commented
> ## Dynamic
> https://github.com/AICoE/internal-data-hub/blob/a401272e2110cfe06316d82c36990dfddf70fed5/obslytics/overlays/dev/verification-cron-workflow.yaml#L12
> 
> ###### This comment was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in [a401272](https://github.com/AICoE/internal-data-hub/commit/a401272e2110cfe06316d82c36990dfddf70fed5) in #56. cc @lucferbux.

yeah, I'm not sure how to convert this, cause it was using ansible facts `"{{ ansible_facts['user_id'] }}@redhat.com"`

2021-06-29 17:51 UTC, anishasthana requested changes
Lots of missing new lines. I haven't yet built and checked yet.

2021-06-29 17:51 UTC, anishasthana commented on argo-workflows/overlays/prod/secret-generator.yaml
> +  - trino-admin-credentials.enc.yaml
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/.sops.yaml
> +    pgp: 'EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E'
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/README.md
> +Kustomize deployment for the Data Hub's internal Obslytics instance
Change it to Data Hub Obslytics workflow

2021-06-29 17:51 UTC, anishasthana commented on obslytics/README.md
> +Run the following command from the `logstash` folder of this repository to deploy
logstash?

2021-06-29 17:51 UTC, anishasthana commented on obslytics/README.md
> +oc new-project dh-dev-ingest
wrong project

2021-06-29 17:51 UTC, anishasthana commented on obslytics/README.md
> +kustomize build --enable_alpha_plugins overlays/${target_env}/ -o build/
Seems like the instructions need tobe updated

2021-06-29 17:51 UTC, anishasthana commented on obslytics/bases/kustomization.yaml
> +  - alert-template.yaml
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/bases/triggers.yaml
> +                    - ceph_cluster_total_bytes
We're missing a few metrics here right?

2021-06-29 17:51 UTC, anishasthana commented on obslytics/bases/triggers.yaml
> +              - ceph_cluster_total_bytes
We have the same list of params in three places. Can we simplify this somehow?

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/dev/backfill-cron-workflow.yaml
> +  value: 3600
Missing new line

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/dev/obslytics-cron-workflow.yaml
> +  value: 3600
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/dev/triggers.yaml
> +    - 4
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/dev/verification-cron-workflow.yaml
> +  value: lferrnan@redhat.com ## TODO: Dynamic
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/prod/backfill-cron-workflow.yaml
> +  value: 86400
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/prod/obslytics-cron-workflow.yaml
> +  value: 86400
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/prod/triggers.yaml
> +    - cluster:usage:consumption:rhods:cpu:seconds:rate5m
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/prod/verification-cron-workflow.yaml
> +  value: data-hub-alerts@redhat.com
Missing newline

2021-06-29 17:51 UTC, anishasthana commented on obslytics/overlays/stage/backfill-cron-workflow.yaml
> +  value: 3600
Missing newline

2021-06-29 19:31 UTC, lucferbux commented
> Lots of missing new lines. I haven't yet built and checked yet.

@anishasthana Oh, damn, sorry, I completely forgot about that 🤦‍♂️

2021-06-29 19:36 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 253f2d05b777850f247ba2f5627019e40a6bc647 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1409957620936085504) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-29 19:48 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | d678297435f733887e2ad1f0ded122775d25ebc3 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1409961074895097856) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-29 19:48 UTC, lucferbux commented on obslytics/README.md
> +kustomize build --enable_alpha_plugins overlays/${target_env}/ -o build/
Is ti becasue right now --enable_alpha_plugins has been renamed to --enable-alpha-plugins? or there's something more i am missing?

2021-06-29 19:55 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 4a10db37ffe8125d1f8b899d7c4f9e97159b3f3a | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1409963167852793856) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-29 19:58 UTC, lucferbux commented on obslytics/bases/triggers.yaml
> +                    - ceph_cluster_total_bytes
mmm there were some metrics commented, should i bring them commented too?
#   - rhods_aggregate_availability  # TODO: uncomment once available
#   - rhods_total_users  # TODO: uncomment once available
#   - cluster_operator_conditions  # TODO: times out, uncomment once grpc proxy allows this

2021-06-29 20:15 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 7aae8603330668c50acffa3f2c2589ae6f04608b | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1409968174908051456) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-29 20:20 UTC, gmfrasca commented on obslytics/bases/triggers.yaml
> +                    - ceph_cluster_total_bytes
i would include commented out metrics as it reminds us we need to uncomment them at some point.

2021-06-29 20:22 UTC, gmfrasca commented on obslytics/bases/triggers.yaml
> +              - ceph_cluster_total_bytes
+1, if we can consolidate params to a single location it will make sure we don't miss or de-sync them on future updates

2021-06-29 20:32 UTC, lucferbux commented on obslytics/bases/triggers.yaml
> +              - ceph_cluster_total_bytes
what would you think is the best approach here @gmfrasca we thought about helm templating but I'm not sure it's the best approach right now. Other option would be some kind of patch with kustomize and leave the base with a simple list, but i'm not sure it's great either.

2021-06-29 20:32 UTC, lucferbux commented on obslytics/bases/triggers.yaml
> +                    - ceph_cluster_total_bytes
Ok perfect!

2021-06-29 20:40 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 7936cb62b0c0d894e73df9e3e558c09f9b80a6f9 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1409974599549980672) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-30 12:28 UTC, lucferbux commented on obslytics/README.md
> +kustomize build --enable_alpha_plugins overlays/${target_env}/ -o build/
@anishasthana is there any more changes apart from the one mentioned above? to close this comment.

2021-06-30 15:14 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 9f723a18f6f6141d100f1cad8f293df4d641f5fe | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1410254929158737920) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-02 14:27 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | d643f5e892be7776afba7aed2ec38c2f7d2bd628 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1410967791388856321) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-02 14:28 UTC, anishasthana commented
/retest

2021-07-02 14:29 UTC, sesheta commented
@lucferbux: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | d643f5e892be7776afba7aed2ec38c2f7d2bd628 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/56/pre-commit/1410968567377039360) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=56). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Alucferbux). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-12 14:38 UTC, anishasthana reviewed
/lgtm

2021-07-12 17:38 UTC, anishasthana reviewed
/lgtm

2021-07-13 15:48 UTC, gmfrasca reviewed
/lgtm

2021-07-13 15:51 UTC, anishasthana approved these changes
/approve

2021-07-13 15:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/internal-data-hub/pull/56#pullrequestreview-705367368" title="Approved">anishasthana</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)~~ [anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-13 16:02 UTC, anishasthana commented
Force merging since ci is down. @lucferbux and @gmfrasca confirmed it works.

2021-07-13 16:02 UTC, merged