Add user that has permissions to pull backups of supersetDB
AICoE/internal-data-hub pull request #86
Opened 2021-09-01 05:11 UTC by maulikjs

2021-09-01 05:11 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **maulikjs** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Finternal-data-hub).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/internal-data-hub/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["maulikjs"]} -->

2021-09-01 05:17 UTC, sesheta commented
@maulikjs: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | e09ef19a2707e97eaaa6657c0e542b4345e1616a | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--e2081a4d-fd23-4347-93d5-f33e0604d95d/prow-logs/pr-logs/pull/AICoE_internal-data-hub/86/pre-commit/1432934179787509761) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=internal-data-hub&pr=86). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Amaulikjs). Please help us and [open an issue](https://github.com/AICoE/internal-data-hub/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 12:07 UTC, rimolive requested changes

2021-09-01 12:07 UTC, rimolive commented on kfdefs/overlays/prod/dh-prod-superset/supersetdb-deployment-pvc-backup.yaml
> +              name: prod-supersetdb-secret
No newline

2021-09-01 12:07 UTC, rimolive commented on kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
> +  - ./supersetdb-deployment-pvc-backup.yaml
No newline

2021-09-01 14:27 UTC, rimolive commented
/lgtm

2021-09-01 15:02 UTC, maulikjs commented
/retest

2021-09-01 16:04 UTC, maulikjs commented
/retest

2021-09-01 17:42 UTC, maulikjs commented
/retest

2021-09-01 17:56 UTC, anishasthana approved these changes

2021-09-01 18:05 UTC, accorvin commented on kfdefs/overlays/prod/dh-prod-superset/supersetdb-deployment-pvc-backup.yaml
> +                  psql '-c' "CREATE USER bareos WITH PASSWORD '$BACKUPS_PASSWORD';";
Will this fail on subsequent deployments of the database pod?

2021-09-02 16:07 UTC, maulikjs commented on kfdefs/overlays/prod/dh-prod-superset/supersetdb-deployment-pvc-backup.yaml
> +                  psql '-c' "CREATE USER bareos WITH PASSWORD '$BACKUPS_PASSWORD';";
Well yeah but if a user already exists it does nothing.

2021-09-02 16:07 UTC, maulikjs commented
/retest

2021-09-07 14:10 UTC, accorvin commented
/approve

2021-09-07 14:24 UTC, rimolive approved these changes

2021-09-07 14:26 UTC, merged